var stateEnum = {
  START_STATE : 0,
  FUNCTION_STATE: 1,
  INVARS_STATE : 2,
  OUTVARS_STATE : 3,
  OTHERVARS_STATE : 4,
  VAR_STATE : 5,
  FUZZ_STATE : 6,
  DEFUZZ_STATE : 7,
  TERM_STATE : 8,
  RULE_BLOCK_STATE : 9,
  RULE_STATE : 10
}
module.exports = stateEnum;